# Generated by Django 5.1.3 on 2024-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_cliente_empleado_zoologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoHabitat', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('area', models.FloatField()),
                ('capacidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoZona', models.CharField(max_length=100)),
            ],
        ),
    ]
