# Generated by Django 5.1.3 on 2024-12-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_habitat_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAlimento', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('especie', models.CharField(max_length=50)),
                ('historialSalud', models.CharField(max_length=50)),
                ('tipoColumnaVertebral', models.CharField(choices=[('Vertebrado', 'Vertebrado'), ('Invertebrado', 'Invertebrado')], max_length=15)),
                ('tipoAlimentacion', models.CharField(choices=[('Carnivoro', 'Carnivoro'), ('Herbivoro', 'Herbivoro'), ('Omnivoro', 'Omnivoro')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conserje',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prueba.empleado')),
                ('areaLimpieza', models.CharField(max_length=50)),
            ],
            bases=('prueba.empleado',),
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prueba.empleado')),
                ('areaResponsable', models.CharField(max_length=50)),
            ],
            bases=('prueba.empleado',),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diagnostico', models.CharField(max_length=100)),
                ('veterinario', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('anamnesis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento'), ('Desocupada', 'Desocupada'), ('Reservada', 'Reservada')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PanelInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=50)),
                ('nombreComun', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=50)),
                ('habitatNatural', models.CharField(max_length=50)),
                ('dieta', models.CharField(max_length=50)),
                ('estadoDeConservacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prueba.empleado')),
                ('especialidad', models.CharField(max_length=50)),
                ('animalCargo', models.CharField(max_length=50)),
            ],
            bases=('prueba.empleado',),
        ),
        migrations.AddField(
            model_name='zoologico',
            name='empleado',
            field=models.ManyToManyField(default=0, related_name='empleados', to='prueba.empleado'),
        ),
        migrations.AddField(
            model_name='zoologico',
            name='zona',
            field=models.ManyToManyField(related_name='zonas', to='prueba.zona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='boleto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='prueba.boleto'),
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prueba.empleado')),
                ('especialidad', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_guia', to='prueba.boleto')),
            ],
            bases=('prueba.empleado',),
        ),
        migrations.CreateModel(
            name='Taquillero',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prueba.empleado')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_taquillero', to='prueba.boleto')),
            ],
            bases=('prueba.empleado',),
        ),
    ]
