# Generated by Django 5.1.3 on 2024-12-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_alimentacion_animal_boleto_conserje_cuidador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conserje',
            name='zona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='zonas_conserje', to='prueba.zona'),
        ),
    ]
